config/routes.rb
Gobeyond::Application.routes.draw do

  devise_for :users

  root :to => "static_pages#home"

  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"

  resources :recommendations

  resources :developments

  resources :challenges

  resources :users do
    resources :profiles
  end
    match '/about',  to: 'static_pages#about'
    match '/help',  to: 'static_pages#help'

end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  attr_accessible :description, :receiver_id, :recommender_id

 belongs_to :recommender, :class_name => 'User'
 belongs_to :receiver, :class_name => 'User'

 default_scope order: 'recommendations.created_at DESC'
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  # GET /recommendations
  # GET /recommendations.json
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @recommendations = Recommendation.all
    @recommendations.recommender = current_user
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recommendations }
    end
  end

  # GET /recommendations/1
  # GET /recommendations/1.json
  def show
    @recommendation = Recommendation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recommendation }
    end
  end

  # GET /recommendations/new
  # GET /recommendations/new.json
  def new
    @recommendation = Recommendation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recommendation }
    end
  end

  # GET /recommendations/1/edit
  def edit
    @recommendation = Recommendation.find(params[:id])
  end

  # POST /recommendations
  # POST /recommendations.json
  def create
    @recommendation = Recommendation.new(params[:recommendation])

    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully created.' }
        format.json { render json: @recommendation, status: :created, location: @recommendation }
      else
        format.html { render action: "new" }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recommendations/1
  # PUT /recommendations/1.json
  def update
    @recommendation = Recommendation.find(params[:id])

    respond_to do |format|
      if @recommendation.update_attributes(params[:recommendation])
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations/1
  # DELETE /recommendations/1.json
  def destroy
    @recommendation = Recommendation.find(params[:id])
    @recommendation.destroy

    respond_to do |format|
      format.html { redirect_to recommendations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/recommendations/_form.html.erb
<%= simple_form_for @recommendation, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :description %>
  <%= f.input :receiver_id %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                recommendations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/recommendations/edit.html.erb
<%- model_class = Recommendation -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/recommendations/index.html.erb
<%- model_class = Recommendation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:recommender_id) %></th>
      <th><%= model_class.human_attribute_name(:receiver_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @recommendations.each do |recommendation| %>
      <tr>
        <td><%= link_to recommendation.id, recommendation_path(recommendation) %></td>
        <td><%= recommendation.description %></td>
        <td><%= recommendation.recommender.try :name %></td>
        <td><%= recommendation.receiver.try :name %></td>
        <td><%=l recommendation.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_recommendation_path(recommendation), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      recommendation_path(recommendation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_recommendation_path,
            :class => 'btn btn-primary' %>

app/views/recommendations/new.html.erb
<%- model_class = Recommendation -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/recommendations/show.html.erb
<%- model_class = Recommendation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @recommendation.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:recommender_id) %>:</strong></dt>
  <dd><%= @recommendation.recommender_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:receiver_id) %>:</strong></dt>
  <dd><%= @recommendation.receiver_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              recommendations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_recommendation_path(@recommendation), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              recommendation_path(@recommendation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>