config/routes.rb
Gobeyond::Application.routes.draw do

  devise_for :users

  root :to => "static_pages#home"

  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"

  resources :recommendations

  resources :developments

  resources :challenges

  resources :users do
    resources :profiles
  end
    match '/about',  to: 'static_pages#about'
    match '/help',  to: 'static_pages#help'

end

app/models/development.rb
class Development < ActiveRecord::Base
  attr_accessible :description, :developer_id, :mentor_id, :priority, :title

  belongs_to :developer, :class_name => 'User'
  belongs_to :mentor, :class_name => 'User'
  default_scope order: 'developments.created_at DESC'
  validates :title, :description, :presence => true
end

app/controllers/developments_controller.rb
class DevelopmentsController < ApplicationController
  # GET /developments
  # GET /developments.json

  before_filter :authenticate_user!, except: [:index, :show]
  
  def index
    @developments = Development.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @developments }
    end
  end

  # GET /developments/1
  # GET /developments/1.json
  def show
    @development = Development.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @development }
    end
  end

  # GET /developments/new
  # GET /developments/new.json
  def new
    @development = Development.new
    @development.developer = current_user
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @development }
    end
  end

  # GET /developments/1/edit
  def edit
    @development = Development.find(params[:id])

  end

  # POST /developments
  # POST /developments.json
  def create
    @development = Development.new(params[:development])
    @development.developer = current_user
    respond_to do |format|
      if @development.save
        format.html { redirect_to @development, notice: 'Development was successfully created.' }
        format.json { render json: @development, status: :created, location: @development }
      else
        format.html { render action: "new" }
        format.json { render json: @development.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /developments/1
  # PUT /developments/1.json
  def update
    @development = Development.find(params[:id])

    respond_to do |format|
      if @development.update_attributes(params[:development])
        format.html { redirect_to @development, notice: 'Development was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @development.errors, status: :unprocessable_entity }
      end
    end
  end

    def add_mentor
    @development = Development.find(params[:id])
    @development.mentor = current_user
    respond_to do |format|
      if @development.update_attributes(params[:development])
        format.html { redirect_to @development, notice: 'Development was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @development.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developments/1
  # DELETE /developments/1.json
  def destroy
    @development = Development.find(params[:id])
    @development.destroy

    respond_to do |format|
      format.html { redirect_to developments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/developments_helper.rb
module DevelopmentsHelper
end

app/views/developments/_form.html.erb
<%= simple_form_for @development, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :priority, collection: ["High", "Medium", "Low"], as: :radio_buttons %>

  <div class="form-actions">
  	<%= f.error :base %>
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                developments_path, :class => 'btn' %>
  </div>
<% end %>

app/views/developments/_mentor.html.erb
<%= simple_form_for @development, :url => {:action => "update"}, :html => { :class => 'form-horizontal' } do |f| %>
  <div><%= f.input :mentor_id, :as => :hidden, :selected => :current_user %></div>
  <%= f.submit "Mentor", class: "btn btn-large btn-primary" %>
<% end %>

app/views/developments/edit.html.erb
<%- model_class = Development -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/developments/index.html.erb
<%- model_class = Development -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:priority) %></th>
      <th><%= model_class.human_attribute_name(:developer_id) %></th>
      <th><%= model_class.human_attribute_name(:mentor_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @developments.each do |development| %>
      <tr>
        <td><%= development.id %></td>
        <td><%= link_to development.title, development_path(development) %></td>
        <td><%= development.description %></td>
        <td><%= development.priority %></td>
        <td><%= development.developer.try :name  %></td>
        <td><%= development.mentor.try :name %></td>
        <td><%=l development.created_at, :format => :short %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_development_path(development), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      development_path(development),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      development_path(development),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_development_path,
            :class => 'btn btn-primary' %>

app/views/developments/new.html.erb
<%- model_class = Development -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/developments/show.html.erb
<%- model_class = Development -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @development.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @development.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:priority) %>:</strong></dt>
  <dd><%= @development.priority %></dd>
  <dt><strong><%= model_class.human_attribute_name(:developer_id) %>:</strong></dt>
  <dd><%= @development.developer.try :name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mentor_id) %>:</strong></dt>
  <dd><%= @development.mentor.try :name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              developments_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_development_path(@development), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              development_path(@development),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

    <%= render :partial => 'mentor' %>