config/routes.rb
Gobeyond::Application.routes.draw do

  devise_for :users

  root :to => "static_pages#home"

  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/help"

  resources :recommendations

  resources :developments

  resources :challenges

  resources :users do
    resources :profiles
  end
    match '/about',  to: 'static_pages#about'
    match '/help',  to: 'static_pages#help'

end

app/views/layouts/_footer.html.erb
<footer>
</br> 
</br>
</br>
    <p>&copy; James Reece 2012</p>
</footer>

app/views/layouts/_media.html.erb
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>

app/views/layouts/_navbar.html.erb
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Gobeyond</a>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
              <li><%= link_to "Challenges", challenges_path  %></li>
              <li><%= link_to "Development", developments_path  %></li>
              <li><%= link_to "About", "/about"  %></li>
              <li><%= link_to "Help", "/help"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <ul class="nav pull-right">
      <div id = "user_nav">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>
          <%= link_to 'Edit profile', edit_user_registration_path %> | 
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Login", new_user_session_path %>
          <% end %>
      </div>
    </ul>

app/views/layouts/_shim.html.erb
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title><%= content_for?(:title) ? yield(:title) : "Gobeyond" %></title>
    <%= csrf_meta_tags %>

<%= render 'layouts/shim' %>
<%= render 'layouts/media' %>

  </head>

  <body>

  <%= render 'layouts/navbar' %>

    <div class="container-fluid">
    <div class="span12">

      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert" href="#">&times;</a>
          <%= msg %>
        </div>
      <% end %>
      <div class="content">
        <div class="row">


    <div class="container">
      <div class="row">
          <div class="span9">
            <%= yield %>
        </div>
      </div><!--/row-->


  <%= render 'layouts/footer' %>
    </div> <!-- /container -->



        <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>